# tools — generate Nushell init files for installed third-party tools
#
# Nushell cannot `eval` shell script, so `eval "$(tool init bash)"` has no
# equivalent: tools emit a .nu file instead. This module writes those files
# into the vendor autoload dir — `$nu.data-dir/vendor/autoload`, the last
# entry of $nu.vendor-autoload-dirs — where Nushell loads them after
# config.nu and before your autoload/ drop-ins.
#
# Installation is the switch: an installed tool gets its file, an absent tool
# gets none and any stale file is deleted. Nothing is commented out. Re-run
# `nu-config tools setup` after installing or upgrading a tool, since init
# output changes between versions.

# The registry. `gen` returns the file contents and only runs when `bin` is
# on PATH. Add a tool by appending a record and running `nu-config tools setup`.
def registry []: nothing -> table {
  [
    {
      name: "zoxide"
      bin: "zoxide"
      what: "frecency cd: `z`, `zi`, PWD hook"
      gen: {|| ^zoxide init nushell }
    }
    {
      name: "atuin"
      bin: "atuin"
      what: "shell history: Ctrl+R full search, Up arrow search seeded with the current line"
      # Up arrow runs atuin with the typed text as the query ("cd" + Up shows
      # cd commands). How it matches is atuin's search_mode_shell_up_key_binding.
      gen: {|| ^atuin init nu }
    }
    {
      name: "carapace"
      bin: "carapace"
      what: "argument completions for ~1000 commands"
      gen: {||
        # Bridges let carapace fall back to other shells' completions.
        [
          "$env.CARAPACE_BRIDGES = 'zsh,fish,bash,inshellisense'"
          (^carapace _carapace nushell)
        ] | str join (char nl)
      }
    }
    {
      name: "vivid"
      bin: "vivid"
      what: "LS_COLORS for `ls`"
      # Baked as a literal: the output is a static ~18 kB string and calling
      # vivid at every startup costs measurable milliseconds for nothing.
      gen: {||
        let theme = ($env.VIVID_THEME? | default "catppuccin-macchiato")
        let colors = (^vivid generate $theme | str trim)
        [
          $"# generated by `nu-config tools setup` from vivid theme ($theme)"
          $"$env.LS_COLORS = ($colors | to nuon)"
          ""
        ] | str join (char nl)
      }
    }
  ]
}

# Where the generated files go.
export def "tools dir" []: nothing -> path {
  $nu.data-dir | path join vendor autoload
}

def file-for [name: string]: nothing -> path {
  tools dir | path join $"($name).nu"
}

# Installed vs generated, per tool.
export def "tools status" []: nothing -> table<tool: string, installed: bool, generated: bool, state: string, what: string> {
  registry | each {|it|
    let has_bin = (which $it.bin | is-not-empty)
    let has_file = (file-for $it.name | path exists)
    {
      tool: $it.name
      installed: $has_bin
      generated: $has_file
      state: (
        if $has_bin and $has_file { "ok" }
        else if $has_bin { "missing: run `nu-config tools setup`" }
        else if $has_file { "stale: run `nu-config tools setup`" }
        else { "not installed" }
      )
      what: $it.what
    }
  }
}

# Generate files for installed tools, remove files for absent ones. Idempotent.
export def "tools setup" [--quiet (-q)]: nothing -> nothing {
  mkdir (tools dir)
  let results = (registry | each {|it|
    let path = (file-for $it.name)
    let has_bin = (which $it.bin | is-not-empty)
    let had_file = ($path | path exists)
    if $has_bin {
      let body = (do $it.gen)
      if ($body | is-empty) {
        { tool: $it.name, action: "failed", detail: "generator produced no output" }
      } else {
        let before = if $had_file { open --raw $path } else { "" }
        $body | save -f $path
        let action = if not $had_file { "created" } else if $before == $body { "unchanged" } else { "updated" }
        { tool: $it.name, action: $action, detail: $path }
      }
    } else if $had_file {
      rm -f $path
      { tool: $it.name, action: "removed", detail: $"($it.bin) is not installed" }
    } else {
      { tool: $it.name, action: "skipped", detail: $"($it.bin) is not installed" }
    }
  })

  let shown = if $quiet { $results | where action not-in [unchanged skipped] } else { $results }
  for r in $shown {
    let colour = (match $r.action {
      "created" | "updated" => (ansi green)
      "removed" => (ansi yellow)
      "failed" => (ansi red)
      _ => (ansi dark_gray)
    })
    print $"  ($colour)($r.action | fill --width 9)(ansi reset) ($r.tool | fill --width 9) ($r.detail)"
  }
  let changed = ($results | where action in [created updated removed] | length)
  if $changed > 0 { print $"($changed) file\(s\) changed — restart Nushell to load them" }
}


def names []: nothing -> list<string> { registry | get name }

# Remove one generated file.
export def "tools remove" [tool: string@names]: nothing -> nothing {
  if $tool not-in (names) { error make { msg: $"unknown tool '($tool)'" } }
  let path = (file-for $tool)
  if ($path | path exists) { rm -f $path; print $"removed ($path)" } else { print $"($tool) has no generated file" }
}
